apiVersion: v1
kind: Service
metadata:
  labels:
    run: spring-boot-hello-world-service-cluster
  name: spring-boot-hello-world-service-cluster
spec:
  ports:
    - protocol: TCP
      port: 5701
      targetPort: 5701
      name: hazelcast
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: application
  type: NodePort
  selector:
    app: spring-boot-hello-world
