apiVersion: v1
kind: Service
metadata:
  labels:
    run: spring-boot-hello-world-service-cluster
  name: spring-boot-hello-world-service-cluster
spec:
  ports:
    - port: 5701
      protocol: TCP
      targetPort: 5701
    #- protocol: TCP
    #  port: 5701
    #  targetPort: 5701
    #  name: hazelcast
    #- protocol: TCP
    #  port: 8080
    #  targetPort: 8080
    #  name: application
  selector:
    app: spring-boot-hello-world
