# headless service
# for more info see: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
apiVersion: v1
kind: Service
metadata:
  labels:
    run: spring-boot-hello-world-service-cluster
  name: spring-boot-hello-world-service-cluster
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5701
      targetPort: 5701
      name: hazelcast
  selector:
    app: spring-boot-hello-world
