apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
  labels:
    app: spring-boot-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - image: codecoder/spring-boot-hello-world:16
        name: spring-boot-hello-world
        ports:
         - containerPort: 8080
           protocol: TCP
           name: application
         - containerPort: 5701
           protocol: TCP
           name: hazelcast
        env:
          - name: spring.profiles.active
            value: hazelcast
          - name: HZ_XML_CONFIG
            #value: hazelcast-kubernetes-restapi.xml <- uncomment this line and comment the line below to switch to rest api discovery variant
            value: hazelcast-kubernetes.xml

